In [171]:
import numpy as np

In [38]:
a=np.array(10)   #1
a

array(10)

In [18]:
x=np.zeros((4,4))   #2
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.ndim(x)             #3
a

2

In [50]:
a=np.arange(15,40)     #4
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

In [53]:
b=a*2                 #5
b

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70, 72, 74, 76, 78])

In [56]:
c=a+b                 #6
c

array([ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
        84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117])

In [62]:
1/c                   #7

array([0.02222222, 0.02083333, 0.01960784, 0.01851852, 0.01754386,
       0.01666667, 0.01587302, 0.01515152, 0.01449275, 0.01388889,
       0.01333333, 0.01282051, 0.01234568, 0.01190476, 0.01149425,
       0.01111111, 0.01075269, 0.01041667, 0.01010101, 0.00980392,
       0.00952381, 0.00925926, 0.00900901, 0.00877193, 0.00854701])

In [61]:
c>50                  #8

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [64]:
c[8]                  #9

69

In [75]:
d=c[c>96]             #10
d

array([ 99, 102, 105, 108, 111, 114, 117])

In [76]:
np.sqrt(d)             #11

array([ 9.94987437, 10.09950494, 10.24695077, 10.39230485, 10.53565375,
       10.67707825, 10.81665383])

In [78]:
np.power(d,2)          #12

array([ 9801, 10404, 11025, 11664, 12321, 12996, 13689], dtype=int32)

In [101]:
np.exp(d)              #13

array([9.88903032e+42, 1.98626484e+44, 3.98951957e+45, 8.01316426e+46,
       1.60948707e+48, 3.23274119e+49, 6.49313426e+50])

In [91]:
x=np.ones((5,5))        #14
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
x[1:-1,1:-1]=0          #15
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
x[1:,1:]+=2             #16
x

array([[1., 1., 1., 1., 1.],
       [1., 4., 4., 4., 4.],
       [1., 4., 4., 4., 4.],
       [1., 4., 4., 4., 4.],
       [1., 4., 4., 4., 4.]])

In [18]:
z=np.random.random((3,3))    #17
z

array([[0.16142849, 0.08827121, 0.11594774],
       [0.88945973, 0.5206696 , 0.71031491],
       [0.33166405, 0.7629733 , 0.9772463 ]])

In [21]:
z.min()                     #18

0.08827120641863528

In [25]:
z.max()                     #19

0.9772463007722437

In [33]:
z.mean()                    #20

0.5064417033591373

In [55]:
z[1:2]**2                   #21

array([[0.79113861, 0.27109684, 0.50454727]])

In [70]:
a=np.array([2,4,3,6,7,9])
a

array([2, 4, 3, 6, 7, 9])

In [119]:
a[::-1]                     #22

array([9, 7, 6, 3, 4, 2])

In [146]:
a = np.arange(-4,8).reshape(4, 3)   #23
a

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [163]:
a[::3]       #24

array([[-4, -3, -2],
       [ 5,  6,  7]])

In [184]:
a[-1,2]=1     #25
a

array([[-4, -3, -2],
       [ 0,  0,  0],
       [ 1,  1,  1],
       [ 5,  6,  1]])

In [44]:
np.linspace(1,3,5)       #26

array([1. , 1.5, 2. , 2.5, 3. ])

In [201]:
y=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [202]:
y[1]=50                 #27
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[50, 50, 50],
        [50, 50, 50]]])

In [244]:
c=np.arange(0,12).reshape(4,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [245]:
c[1:3,2:3]           #28

array([[5],
       [8]])

In [7]:
u=[-3,-2,0,1,2,4,6,7,9]

In [8]:
v=[-2,1,3,5,7,8,9,10,11]

In [9]:
w=np.intersect1d(u,v)    #29
w

array([-2,  1,  7,  9])

In [10]:
np.where(w)              #30

(array([0, 1, 2, 3], dtype=int64),)

In [21]:
np.setdiff1d(u,v)        #31

array([-3,  0,  2,  4,  6])

In [15]:
k=np.concatenate((u,v))   #32
k

array([-3, -2,  0,  1,  2,  4,  6,  7,  9, -2,  1,  3,  5,  7,  8,  9, 10,
       11])

In [16]:
k[k%2==1]                 #33

array([-3,  1,  7,  9,  1,  3,  5,  7,  9, 11])

In [18]:
k[k%2==0]                 #34

array([-2,  0,  2,  4,  6, -2,  8, 10])

In [20]:
np.where(k%2==1,-1,k)      #35

array([-1, -2,  0, -1,  2,  4,  6, -1, -1, -2, -1, -1, -1, -1,  8, -1, 10,
       -1])

In [39]:
j=np.arange(12).reshape(4,3)
j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
j[[0,3,2,1,],:]            #36

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [71]:
j[[0],:]+2                 #37

array([[2, 3, 4]])

In [73]:
m=np.arange(20)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
np.set_printoptions(threshold=8)   #38

In [91]:
m=np.arange(20)
m

array([ 0,  1,  2, ..., 17, 18, 19])

In [101]:
np.where(m<5,4,np.where(m>15,3,m))   #39

array([4, 4, 4, ..., 3, 3, 3])

In [104]:
np.random.seed(50)

In [110]:
a=np.random.uniform(1,10)            #40
a

2.0107646527460616

In [111]:
np.sin(a)                            #41

0.9047651539935344

In [119]:
a=np.arange(3)
b=np.arange(1,4)                     #42
c=np.arange(0,2,5)

In [126]:
d=np.array([a,b,c])                  #43
d

array([array([0, 1, 2]), array([1, 2, 3]), array([0])], dtype=object)

In [140]:
x=np.zeros((7,7))
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [141]:
x+=np.arange(7)                    #44
x

array([[0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       ...,
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.],
       [0., 1., 2., ..., 4., 5., 6.]])

In [143]:
y=np.random.random(15)              #45
y.sort()
y

array([0.05225869, 0.05640164, 0.17982769, ..., 0.88820004, 0.92593317,
       0.92800093])

In [146]:
Z=np.arange(20)                     #46
np.add.reduce(Z)

190

In [150]:
a=np.random.random(8)               #47
a[a.argmax()]=0
a

array([0.        , 0.1786192 , 0.22711417, 0.65987645, 0.47911625,
       0.07344734, 0.13896007, 0.11230718])

In [154]:
m= [0,2,4,6,8]                      #48
n= [1,3,5,7,9]
r= np.bincount(m,n)
r

array([1., 0., 3., ..., 7., 0., 9.])

In [164]:
a= np.arange(25).reshape(5,5)       #49
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [173]:
z=np.random.randint(0,15,35)        #50
print(np.bincount(z).argmax())

1
